# sam-bcada/app/coordinator/Dockerfile
FROM golang:1.21-alpine AS build
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o coordinator main.go

FROM alpine
WORKDIR /app
COPY --from=build /app/coordinator .
EXPOSE 8080
CMD ["./coordinator"]
